#! /bin/sh

sxhkd &
~/.fehbg
setxkbmap pl &
flameshot &
picom -b &
sh ~/.config/polybar/launch.sh

bspc monitor HDMI-1 -d HOME CODE CHAT MUSIC WEB       

bspc config border_width         0
bspc config window_gap          40

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
