username = '11175575318'
auth_type = 1
auth_data = 'QVFCMnlCdFMtSTVDelFWTkthMkwyM3NucmVYbUlRUkQ5eDQzcm9odnRxLVFPYXU0RFhfR3JXdXR2aEo5YldjX19xYWVxRnE3S2ZGWlQ0RmNPM1BuanV1UmpnM1k3OEE5c1hKTTVyNjk4WW5rczV4UjFsM1FKNEQ1eHF4akVSZVhUWnM0V3RsSm1POE0='
